# Generated by Django 3.0.7 on 2020-07-01 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('FICTION', (('cla', 'Classic'), ('nov', 'Novel'), ('dra', 'Drama'), ('fab', 'Fable'), ('ft', 'Fairy Tail'), ('fant', 'Fantasy'), ('fic', 'Fiction'), ('folk', 'Folkore'), ('hfic', 'Historical fiction'), ('hor', 'Horror'), ('leg', 'Legend'), ('mystery', 'Mystery'), ('poe', 'Poetry'), ('myth', 'Mythology'), ('romance', 'Romancd'), ('sat', 'Satire'), ('shortstory', 'Shortstory'), ('swb', 'Swashbuckler'), ('thr', 'Thriller'), ('trv', 'Travel'), ('west', 'Western'), ('sfic', 'Science Fiction'), ('rfic', 'Realistic Fiction'), ('hum', 'Humor'))), ('NONFICTION', (('bio', 'Biography'), ('ess', 'Essay'), ('journalism', 'Journalism'), ('memoire', 'Memoir'), ('nnf', 'Narrative non fiction'), ('refbook', 'Reference Book'), ('selfhbook', 'Self Help Book'), ('speech', 'Speech'), ('textbook', 'textbook'))), ('Image Books', (('comics', 'Comics'), ('bd', 'Bd'), ('mangas', 'Mangas'))), ('OTHER', (('other', 'Other Genre'),))], default='cla', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('ger', 'German'), ('ar', 'Arabic'), ('fr', 'French'), ('sp', 'Spanish'), ('jap', 'Japanese'), ('it', 'Italian'), ('ru', 'Russian'), ('jap', 'Japanese'), ('chi', 'Chinese')], default='en', max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Author (if not you)')),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('cover', models.ImageField(default='cover/default_cover.jpg', upload_to='cover')),
                ('original_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
