# Generated by Django 3.0.7 on 2020-07-02 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 16, 13, 9, 275449, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
