# Generated by Django 3.0.7 on 2020-07-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
