# Generated by Django 3.0.7 on 2020-07-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_books_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf_files'),
        ),
    ]
