# Generated by Django 3.0.7 on 2020-07-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pdf',
            field=models.FileField(default='populate_pdf/dummy.pdf', upload_to='pdf_files'),
            preserve_default=False,
        ),
    ]
