# Generated by Django 3.0.7 on 2020-07-04 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200704_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
