# Generated by Django 3.0.7 on 2020-07-04 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200704_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
