# Generated by Django 3.0.7 on 2020-07-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_billingaddress_auto_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='saved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
