# Generated by Django 3.0.7 on 2020-07-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200710_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='P', max_length=200),
            preserve_default=False,
        ),
    ]
