# Generated by Django 3.0.7 on 2020-07-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
